project_id = "bnydsueacjdhxvweosoe"

[auth]
# Set OTP expiry to recommended 10 minutes (600 seconds)
otp_expiry = 600

# Enable stronger password requirements
password_min_length = 8
password_require_letters = true
password_require_numbers = true
password_require_symbols = true  
password_require_uppercase = true
password_require_lowercase = true

# Enable leaked password protection
enable_leaked_password_protection = true